spring:
  application:
    name: otboo

otboo:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_SECRET:your-access-token-secret-key-here-make-it-long-and-random}
      expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:1800000}
    refresh-token:
      secret: ${JWT_REFRESH_SECRET:your-refresh-token-secret-key-here-make-it-different-and-long}
      expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}


management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
  metrics:
    tags:
      application: ${spring.application.name}
