spring:
  application:
    name: otboo

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
  metrics:
    tags:
      application: ${spring.application.name}
